### ISSUE TITLE
Not working with 'node-rest-client'

### ISSUE THREAD

**Issue by airsidemap** [frankred/node-full-text-search-light#6]
Hello
The module is not working combined with 'node-rest-client'. 
If fulltextsearchlight is loaded bevor node-rest-client, the following error occurs at startup: 
```
C:\Daten\aaa\node_modules\node-rest-client\lib\nrc-parser-manager.js:10
var propType  = props[propIndex].split(":");

TypeError: props[propIndex].split is not a function
    at validateProperties (C:\Daten\aaa\node_modules\node-rest-client\lib\nrc-parser-manager.js:10:39)
    at Object.validate (C:\Daten\aaa\node_modules\node-rest-client\lib\nrc-parser-manager.js:21:13)
    at ParserManager.add (C:\Daten\aaa\node_modules\node-rest-client\lib\nrc-parser-manager.js:34:17)
    at module.exports (C:\Daten\aaa\node_modules\node-rest-client\lib\nrc-parser-manager.js:112:15)
    at new exports.Client (C:\Daten\aaa\node_modules\node-rest-client\lib\node-rest-client.js:12:53)
    at Object.<anonymous> (C:\Daten\aaa\index.js:15:14)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
```

If fulltextsearchlight is loaded after node-rest-client, the program starts normal, but the output of node-rest-client is somehow corrupted.

**Comment by airsidemap** [comment]
I also opened the issue in the node-rest-client repository and got an answer from them. The problem seems to be this function at the beginning of index.js:

```
Array.prototype.unique = function () {
    var a = [];
    for (var i = 0, l = this.length; i < l; i++) {
        if (a.indexOf(this[i]) === -1) {
            a.push(this[i]);
        }
    }
    return a;
};

```
This function is added to every array as an element.

I hope this will help someone.

**Comment by frankred** [comment]
Hi @airsidemap,

thank you for finding the problem. I think prototyping the Array object is not a good idea. I should fix that.

**Comment by frankred** [comment]
I just fixed the problem and created a new release. Can you retest it with npm version @0.0.17?

**Comment by Palavesh** [comment]
Same issue here, any fix available?

Array.prototype.contains = function(obj) {
    var i = this.length;
    while (i--) {
        if (this[i] === obj) {
            return true;
        }
    }
    return false;
}

**Comment by droidmanspace** [comment]
I am also facing this on the remote server , but it works fine in my local.

**Comment by frankred** [comment]
Thanks, I will fix soon!

**Comment by frankred** [comment]
Have you installed the version @0.0.17? In version 0.0.17 there is no Array.prototype.contains anymore.
@droidmanspace @Palavesh
